### ISSUE TITLE
Zmiana rest

### ISSUE THREAD

**Issue by mrozim78** [OtwartaPlatformaWyborcza/OPW-dashboard-jQuery#2]
Moim zdaniem rest powinien zawierać już przeliczone dane procentowe:
- dla frekwencji
- dla wyniku pojedynczego kandydata
  Powód:
  Złamanie zasad bezpieczeństwa i rozcięcie systemu i zawierzenie przeliczenia danych stronie klienta. Jest to złamanie zasady , że stronie klienta się nie ufa i zawsze się weryfikuje to co wykonuje. Co do wydajności nie jest to uzasadnione moim zdaniem można dopuścić tu sytuacje przeliczania okresowo takich danych na serwerze. Poza tym nie wyobrażam sobie takiego samego patentu jak już będzie można wyświetlać dane z dokładnością do okręgu czy lokalu.

**Comment by Krzyku** [comment]
Dashboard i tak jeśli o kandydatów chodzi wyświetla wyniki jako liczby (ilość głosów) i procenty.
Co do tego bezpieczeństwa to chyba Cie trochę nie rozumiem bo czy dostanie liczby w formie procenta czy 'czystej' to jeden pies...
Rozumiem jak by miał je później znów wysyłać na serwer ale przecież tak nie jest. Przeglądarka łapie dane, generuje z nich wykresy i koniec.
