### ISSUE TITLE
Poprawka rest

### ISSUE THREAD

**Issue by mrozim78** [OtwartaPlatformaWyborcza/OPW-dashboard-jQuery#3]
Jawne wysyłanie restem kolejności kandydata na liście. Jest to o  tyle istotne , że zgodne z sytuacją rzeczywistą nie można przyjąć w żadnym razie kolejności alfabetycznej. A tylko tą którą narzuciła ( wybrało zgodnie z odpowiednimi przepisami ) PKW.

**Comment by Krzyku** [comment]
Ale PKW wielu wyborów (m.in. prezydenckich) narzuca kolejność alfabetyczną.
Innymi przypadkami będziemy się martwić po drugiej turzy gdy zaczniemy pracę nad jesiennymi wyborami.
